### ISSUE TITLE
X64dbg

### ISSUE THREAD

**Issue by ddkwork** [GregoryMorse/GhidraDec#3]
How to build for x64dbg?

**Comment by GregoryMorse** [comment]
For x64dbg, you would have to extract the two files sleighinterface.cpp and sleightinterface.h which contain most of the protocol interaction and then you would have to custom implement the interface as decompiler.cpp and decompiler.h do now.  So please look at these source files.  This codebase can be used to create an x64dbg plugin and this would be quite a good idea to move ahead with.  I might look into it if time ever allows.
