### ISSUE TITLE
Plugin does not seem to show decompile?

### ISSUE THREAD

**Issue by biggestsonicfan** [GregoryMorse/GhidraDec#4]
Greetings,

Decided to give this a spin and the only Output provided in IDA after using `Ctrl+G` is as follows:
```
Executing action: Edit/Plugins/Ghidra Decompiler (Ghidra Decompiler)
[GhidraDec info]   :	Found decompile.exe at C:\ghidra\ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/os/win_x86_64/ -> plugin is properly configured.
[GhidraDec info]   :	Working on input file "C:\stf_rom\sfight\rom_code1.bin".
```

After this nothing seems to happen. I'm not sure where the visual representation of decompiled code would appear.

I'm using IDA 7.7 Pro with Ghidra 10.1.2. Plugin was compiled with using "win_bison 3.7.4", "win_flex 2.6.4", "cmake 3.23.1" and "Visual Studio 16 2019".

I am, however, using a processor [not natively supported by Ghidra](https://github.com/mumbel/ghidra_i960), but _is_ natively supported by IDA, if that makes any difference. The processor, compiler, and sleigh specs are all set as well to their respective i960 language files.

**Comment by GregoryMorse** [comment]
If your ldefs file does not contain the IDA binding, then it will not work more than likely this is the issue.

e.g.: https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/ARM/data/languages/ARM.ldefs
```
<language_definitions>
...
    <external_name tool="IDA-PRO" name="arm"/>
...
</language_definitions>
```

You have to dig out IDA's internal processor name likely "i960" but I'm not sure.  This can be done with a line of idapython code something like `idaapi.get_inf_structure().procName`.

**Comment by biggestsonicfan** [comment]
Ah, that definitely seemed to get it further!

Now I appear to be getting a `Decompilation FAILED: Sleigh xml file not found or could not be parsed syntax error.` with the following output:
```
Executing action: Edit/Plugins/Ghidra Decompiler (Ghidra Decompiler)
[GhidraDec info]   :	Found decompile.exe at C:\ghidra\ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/os/win_x86_64/ -> plugin is properly configured.
[GhidraDec info]   :	Working on input file "C:\stf_rom\sfight\rom_code1.bin".
[GhidraDec info]   :	Running Ghidra decompiler plugin:
[GhidraDec info]   :	Saving IDA database ...
Flushing buffers, please wait...ok
[GhidraDec info]   :	IDA database saved into :  C:\stf_rom\sfight\rom_code1.bin.dec-backup.idb
[GhidraDec info]   :	Generating retargetable decompilation DB ...
[GhidraDec info]   :	Decompile input ...
[GhidraDec info]   :	Decompilation command: C:\ghidra\ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/os/win_x86_64/decompile.exe
[GhidraDec info]   :	Running the decompilation command ...
[GhidraDec info]   :	Detected Processor spec: C:\ghidra\ghidra_10.1.2_PUBLIC\Ghidra\Processors\80960\data\languages\i960.pspec Compiler spec: C:\ghidra\ghidra_10.1.2_PUBLIC\Ghidra\Processors\80960\data\languages\i960.cspec Sleigh file: C:\ghidra\ghidra_10.1.2_PUBLIC\Ghidra\Processors\80960\data\languages\i960.slaspec
[GhidraDec info]   :	Local decompilation ...
```

**Comment by GregoryMorse** [comment]
Make sure the file is present and valid syntax:
C:\ghidra\ghidra_10.1.2_PUBLIC\Ghidra\Processors\80960\data\languages\i960.slaspec

Also it requires a bunch of things defined e.g. what is in the ARM.  Perhaps its looking for some XML key that does not exist?

**Comment by GregoryMorse** [comment]
Sorry it requires a compiled sleigh file.  it should be i960.sla.  Not i960.slaspec which is not yet compiled to XML.  See a full built Ghidra 10.1.2 package.  Check ghidra_10.1.2_PUBLIC\Ghidra\Processors\ARM\data\languages:
there are many ARM*.sla files.

Then it should work.

**Comment by biggestsonicfan** [comment]
That did the trick, cheers! You now know GhidraDec can work with custom processors! :clinking_glasses: :tada:
